### ISSUE TITLE
如何监听打印的确定和取消的按钮事件

### ISSUE THREAD

**Issue by FifteenSc** [laixiangran/essence-ng2-print#4]
在插件使用过程中，我们发现需要对用户打印操作的确认和取消按钮点击事件进行监听，以完成某种回调函数，目前没有找到合适的解决办法。望大佬指点迷津

**Comment by laixiangran** [comment]
@FifteenSc 你说的是进入到浏览器自带的那个打印页面吗？这里面的操作目前无法监听到，浏览器不支持

**Comment by FifteenSc** [comment]
@laixiangran 好吧，我自己也有搜相关的技术点，确实要无法监听浏览器自身打印的按钮点击事件。Whatever，Thank you。
